### ISSUE TITLE
raspystat-config.json missing

### ISSUE THREAD

**Issue by BatteryDie** [Willseph/raspystat#6]
Hey!

I got controller, sensor, and web server running without https but I am having trouble with login account. It seem they do not have created account. My guess is raspystat-config.json contains username and password options after I looked config.php mentioned raspystat-config.json but this repo do not have it. Are there way to get raspystat-config.json?

**Comment by Willseph** [comment]
The user credentials are actually stored within the MySQL database, not within a json config file. If you look in the database via phpMyAdmin or another MySQL viewer, assuming your webserver is running correctly, you should see a table called `users`, which is where the username, salt, and hashed+salted password are stored.

I haven't maintained this project for a while unfortunately but I'll do my best to help get it up and running for you. I'm looking through my own home implementation right now and I'm not seeing a `raspystat-config.json` file either, but the code in `config.php` should still work if you added one.

Your two best options are probably either:
1. Change the auth settings to allow anonymous LAN access (if your home environment is safe to do so).
2. Create your own user credentials manually.

For option 1, you will need to create a `raspystat-config.json` file on your webserver. I believe the file needs to exist one level above the root `raspystat` directory. So for example if your installation exists somewhere like `/var/www/html/raspystat`, then your config file should be at `/var/www/raspystat-config.json`.

I don't remember exactly what options are all available for that file, but looking at `config.php`, you should be able to allow anonymous LAN access with this JSON:
```
{
   "tlsIgnored": true,
   "allowLanGuests": true
}
```
After adding that, guests accessing the web interface over a LAN address (assuming it starts with `192.168.`) should be able to see it. If your LAN doesn't use that address prefix for devices, you'll need to modify the `isLan` function of `config.php` to account for that.

For option 2, if you don't want anonymous LAN access enabled, you will need to manually add your username, salt, and hash to the `users` table of the DB. I never got around to creating a web-based account creator thing sadly, but doing it manually shouldn't be too bad.

Looking at [auth-utils.php](https://github.com/Willseph/raspystat/blob/master/web/raspystat/core/lib/auth-utils.php), the salt is a 32-character arbitrary alphanumeric string, and the hashed password is in the format **sha512 (*S**P*)**, where *S* is your salt string and *P* is your plaintext password. In other words, the hash is generated by taking a concatenated string of your salt and your password (with no separator characters in between) and hashing it with the SHA-512 algorithm just once.

If you are adding a user for yourself, I would also recommend setting the `admin` value of the new user row to `1`.

I hope that helps out, if you run into any follow-up issues, I'll do my best to get it working!
